# Generated by Django 5.2.16 on 2026-07-12 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('records_ingested', models.PositiveIntegerField(default=0)),
                ('records_healed', models.PositiveIntegerField(default=0)),
                ('records_quarantined', models.PositiveIntegerField(default=0)),
                ('fault_counts', models.JSONField(blank=True, default=dict, help_text="Per fault-type counts, e.g. {'missing_value': 12}")),
                ('cdqi_scores', models.JSONField(blank=True, default=dict, help_text='ISO 25012 dimensions (completeness/accuracy/consistency/timeliness/uniqueness) plus the composite score, before and after healing.')),
                ('notes', models.TextField(blank=True)),
                ('triggered_by', models.ForeignKey(blank=True, help_text='Null for Celery Beat-scheduled runs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_pipeline_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
