# Generated by Django 5.2.16 on 2026-07-12 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_reference', models.CharField(blank=True, max_length=128)),
                ('column_name', models.CharField(blank=True, max_length=64)),
                ('fault_type', models.CharField(blank=True, choices=[('missing_value', 'Missing Value'), ('duplicate_record', 'Duplicate Record'), ('schema_drift', 'Schema Drift'), ('statistical_outlier', 'Statistical Outlier'), ('type_error', 'Type Error'), ('range_violation', 'Range Violation'), ('format_inconsistency', 'Format Inconsistency'), ('referential_integrity', 'Referential Integrity Fault')], max_length=32)),
                ('strategy_applied', models.CharField(blank=True, max_length=64)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('narrative', models.TextField(blank=True, help_text='Plain-language explanation from M6 (Jinja2 template, extended via Groq for multi-fault rows).')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('pipeline_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='etl.pipelinerun')),
            ],
            options={
                'verbose_name_plural': 'audit log entries',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['pipeline_run', 'occurred_at'], name='core_auditl_pipelin_adc6c5_idx')],
            },
        ),
    ]
