# Generated by Django 5.2.16 on 2026-07-12 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_customer_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('country', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ['external_customer_id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock_code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['stock_code'],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_no', models.CharField(db_index=True, max_length=32)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('invoice_date', models.DateTimeField(db_index=True)),
                ('is_cancellation', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='warehouse.customer')),
                ('source_batch', models.ForeignKey(blank=True, help_text='Which pipeline run loaded this row - full raw-to-dashboard traceability (NFR-07).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='etl.pipelinerun')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='warehouse.product')),
            ],
            options={
                'ordering': ['-invoice_date'],
                'indexes': [models.Index(fields=['product', 'invoice_date'], name='warehouse_o_product_6117aa_idx'), models.Index(fields=['customer', 'invoice_date'], name='warehouse_o_custome_9304cd_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='orderline_unit_price_non_negative')],
            },
        ),
    ]
