# Generated by Django 5.2.16 on 2026-07-12 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etl', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarantineRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_reference', models.CharField(help_text='Source-row identifier (e.g. invoice_no:stock_code) - not an FK, since a quarantined row failed validation and may not be a real warehouse record yet.', max_length=128)),
                ('fault_code', models.CharField(choices=[('missing_value', 'Missing Value'), ('duplicate_record', 'Duplicate Record'), ('schema_drift', 'Schema Drift'), ('statistical_outlier', 'Statistical Outlier'), ('type_error', 'Type Error'), ('range_violation', 'Range Violation'), ('format_inconsistency', 'Format Inconsistency'), ('referential_integrity', 'Referential Integrity Fault')], max_length=32)),
                ('column_name', models.CharField(blank=True, max_length=64)),
                ('raw_value', models.TextField(blank=True, help_text='Original value, stored as text since source type varies.')),
                ('recommended_action', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('edited_and_approved', 'Edited and Approved')], default='pending', max_length=24)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('pipeline_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarantine_records', to='etl.pipelinerun')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_quarantine_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'fault_code'], name='healing_qua_status_bb5d33_idx')],
            },
        ),
    ]
